<a id="System"> </a>
# Recommendation System

### Popularity Based Recommendation

#### Import the basic libraries

In [1]:
import pandas as pd
import numpy as np

#### Reading the movie_dataset.csv

In [2]:
data=pd.read_csv('book.csv')

In [3]:
data.head()

,Unnamed: 0,userID,ISBN,bookRating,bookTitle,totalRatingCount,Location
0,0,276725,034545104X,0,Flesh Tones: A Novel,60,"tyler, texas, usa"
1,1,2313,034545104X,5,Flesh Tones: A Novel,60,"cincinnati, ohio, usa"
2,2,6543,034545104X,0,Flesh Tones: A Novel,60,"strafford, missouri, usa"
3,3,8680,034545104X,5,Flesh Tones: A Novel,60,"st. charles county, missouri, usa"
4,4,10314,034545104X,9,Flesh Tones: A Novel,60,"beaverton, oregon, usa"

In [4]:
data.shape

(26500, 7)

### Popularity Based Recommendation System

In [5]:
# Top 10 books interms of average rating 

pd.DataFrame(data.groupby('bookTitle')['bookRating'].mean().sort_values(ascending=False)).head(10)

                                                    bookRating
bookTitle
Das Parfum: Die Geschichte Eines Morders             10.000000
Matilda                                               8.000000
Harry Potter and the Chamber of Secrets (Book 2)      6.720588
MÃ?Â¶rder ohne Gesicht.                               6.500000
Ender's Game (Ender Wiggins Saga (Paperback))         5.857143
Sabine's Notebook: In Which the Extraordinary C...    5.785714
The Cat in the Hat                                    5.734694
Harry Potter and the Order of the Phoenix (Book 5)    5.565693
City of Bones                                         5.325581
Into the Forest                                       5.206897

In [6]:
popularity_table=data.groupby('bookTitle').agg({'bookRating':'mean','totalRatingCount':'count'})

In [7]:
popularity_table

,bookRating,totalRatingCount
bookTitle,,
1st to Die: A Novel,3.415301,366
"A Child Called \It\"": One Child's Courage to Survive""",4.139738,229
A Cold Heart: An Alex Delaware Novel,3.112903,62
A Kiss of Shadows (Meredith Gentry Novels (Paperback)),4.013333,75
A Man in Full,2.111111,90
...,...,...
Whispers,1.984615,65
White Teeth: A Novel,2.555556,117
Wild Animus,1.055014,1436
Winter Solstice,2.966667,90
Writ of Execution,2.950000,80

In [8]:
#consider the books for recommendation only if it has 100 rating counts
top_popularity_table=popularity_table[popularity_table['totalRatingCount']>100]
top_popularity_table

,bookRating,totalRatingCount
bookTitle,,
1st to Die: A Novel,3.415301,366
"A Child Called \It\"": One Child's Courage to Survive""",4.139738,229
A Painted House,3.260870,736
A Wrinkle In Time,4.569444,144
All Around the Town,2.946970,132
...,...,...
To Kill a Mockingbird,4.761329,331
Violets Are Blue,2.777778,225
While I Was Gone,2.740964,332
White Teeth: A Novel,2.555556,117
Wild Animus,1.055014,1436

In [9]:
#Top 10 books to recommed based on popularity
top_popularity_table.sort_values('bookRating',ascending=False).head(10)

,bookRating,totalRatingCount
bookTitle,,
Harry Potter and the Chamber of Secrets (Book 2),6.720588,136
Harry Potter and the Order of the Phoenix (Book 5),5.565693,274
Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback)),4.850598,502
To Kill a Mockingbird,4.761329,331
The Da Vinci Code,4.699329,745
The Lovely Bones: A Novel,4.622624,1052
Fahrenheit 451,4.615120,291
A Wrinkle In Time,4.569444,144
Girl with a Pearl Earring,4.319648,341
The Notebook,4.307692,104

In [10]:
#Top 10 books to recommed based on popularity
top_popularity_table.sort_values('totalRatingCount',ascending=False).head(10)

,bookRating,totalRatingCount
bookTitle,,
Wild Animus,1.055014,1436
The Lovely Bones: A Novel,4.622624,1052
The Da Vinci Code,4.699329,745
A Painted House,3.260870,736
The Summons,3.375421,594
The Pilot's Wife : A Novel,3.598814,506
Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback)),4.850598,502
The Joy Luck Club,3.105033,457
She's Come Undone (Oprah's Book Club),3.580569,422
She's Come Undone (Oprah's Book Club (Paperback)),3.481572,407

<a id="System4"> </a>

###  Content-based recommendation system

In [11]:
data1=pd.read_csv('movie_metadata.csv')

In [12]:
data1.head(2)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0

In [13]:
data1.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [14]:
data1["genres"]

0       Action|Adventure|Fantasy|Sci-Fi
1              Action|Adventure|Fantasy
2             Action|Adventure|Thriller
3                       Action|Thriller
4                           Documentary
                     ...
5038                       Comedy|Drama
5039       Crime|Drama|Mystery|Thriller
5040              Drama|Horror|Thriller
5041               Comedy|Drama|Romance
5042                        Documentary
Name: genres, Length: 5043, dtype: object

In [15]:
genres=data1['genres'].str.split('|',expand=True)
#genere=data1["genres"].str.split('|')
#genres
genres=genres.iloc[:,0:3]

In [16]:
genres

                0          1         2
0          Action  Adventure   Fantasy
1          Action  Adventure   Fantasy
2          Action  Adventure  Thriller
3          Action   Thriller      None
4     Documentary       None      None
...           ...        ...       ...
5038       Comedy      Drama      None
5039        Crime      Drama   Mystery
5040        Drama     Horror  Thriller
5041       Comedy      Drama   Romance
5042  Documentary       None      None

[5043 rows x 3 columns]

In [17]:
genres=genres.fillna('Others')

In [18]:
genres

                0          1         2
0          Action  Adventure   Fantasy
1          Action  Adventure   Fantasy
2          Action  Adventure  Thriller
3          Action   Thriller    Others
4     Documentary     Others    Others
...           ...        ...       ...
5038       Comedy      Drama    Others
5039        Crime      Drama   Mystery
5040        Drama     Horror  Thriller
5041       Comedy      Drama   Romance
5042  Documentary     Others    Others

[5043 rows x 3 columns]

In [19]:
genres.columns=['genre1','genre2','genre3']
genres.head(10)

        genre1     genre2    genre3
0       Action  Adventure   Fantasy
1       Action  Adventure   Fantasy
2       Action  Adventure  Thriller
3       Action   Thriller    Others
4  Documentary     Others    Others
5       Action  Adventure    Sci-Fi
6       Action  Adventure   Romance
7    Adventure  Animation    Comedy
8       Action  Adventure    Sci-Fi
9    Adventure     Family   Fantasy

In [20]:
data1=pd.concat([data1,genres],axis=1)

In [21]:
data1.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,genre1,genre2,genre3
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,Action,Adventure,Fantasy
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,Action,Adventure,Fantasy
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,Action,Adventure,Thriller
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,Action,Thriller,Others
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,12.0,7.1,NaN,0,Documentary,Others,Others

In [22]:
#movie_feat=['movie_title','genre1','genre2','genre3','language','content_rating',
           #'imdb_score','num_user_for_reviews','movie_facebook_likes']

In [23]:
movie_feat=['movie_title','genre1','genre2','genre3','content_rating','imdb_score']

In [24]:
data2=data1[movie_feat]

In [25]:
data2.head(2)

,movie_title,genre1,genre2,genre3,content_rating,imdb_score
0,Avatar,Action,Adventure,Fantasy,PG-13,7.9
1,Pirates of the Caribbean: At World's End,Action,Adventure,Fantasy,PG-13,7.1

In [26]:
data2.shape

(5043, 6)

In [27]:
data2=data2.drop_duplicates()

In [28]:
data2.index=data2['movie_title']

In [29]:
data2

,movie_title,genre1,genre2,genre3,content_rating,imdb_score
movie_title,,,,,,
Avatar,Avatar,Action,Adventure,Fantasy,PG-13,7.9
Pirates of the Caribbean: At World's End,Pirates of the Caribbean: At World's End,Action,Adventure,Fantasy,PG-13,7.1
Spectre,Spectre,Action,Adventure,Thriller,PG-13,6.8
The Dark Knight Rises,The Dark Knight Rises,Action,Thriller,Others,PG-13,8.5
Star Wars: Episode VII - The Force Awakens,Star Wars: Episode VII - The Force Awakens ...,Documentary,Others,Others,NaN,7.1
...,...,...,...,...,...,...
Signed Sealed Delivered,Signed Sealed Delivered,Comedy,Drama,Others,NaN,7.7
The Following,The Following,Crime,Drama,Mystery,TV-14,7.5
A Plague So Pleasant,A Plague So Pleasant,Drama,Horror,Thriller,NaN,6.3
Shanghai Calling,Shanghai Calling,Comedy,Drama,Romance,PG-13,6.3
My Date with Drew,My Date with Drew,Documentary,Others,Others,PG,6.6

In [30]:
data2=data2.drop('movie_title',axis=1)

In [31]:
data2.head(2)

,genre1,genre2,genre3,content_rating,imdb_score
movie_title,,,,,
Avatar,Action,Adventure,Fantasy,PG-13,7.9
Pirates of the Caribbean: At World's End,Action,Adventure,Fantasy,PG-13,7.1

In [32]:
data3=pd.get_dummies(data2)# one hot encoding

In [33]:
data3.head()

,imdb_score,genre1_Action,genre1_Adventure,genre1_Animation,genre1_Biography,genre1_Comedy,genre1_Crime,genre1_Documentary,genre1_Drama,genre1_Family,...,content_rating_Passed,content_rating_R,content_rating_TV-14,content_rating_TV-G,content_rating_TV-MA,content_rating_TV-PG,content_rating_TV-Y,content_rating_TV-Y7,content_rating_Unrated,content_rating_X
movie_title,,,,,,,,,,,,,,,,,,,,,
Avatar,7.9,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Pirates of the Caribbean: At World's End,7.1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Spectre,6.8,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
The Dark Knight Rises,8.5,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Star Wars: Episode VII - The Force Awakens,7.1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
data3.shape

(4920, 89)

In [35]:
data3=data3.dropna()
data3

,imdb_score,genre1_Action,genre1_Adventure,genre1_Animation,genre1_Biography,genre1_Comedy,genre1_Crime,genre1_Documentary,genre1_Drama,genre1_Family,...,content_rating_Passed,content_rating_R,content_rating_TV-14,content_rating_TV-G,content_rating_TV-MA,content_rating_TV-PG,content_rating_TV-Y,content_rating_TV-Y7,content_rating_Unrated,content_rating_X
movie_title,,,,,,,,,,,,,,,,,,,,,
Avatar,7.9,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Pirates of the Caribbean: At World's End,7.1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Spectre,6.8,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
The Dark Knight Rises,8.5,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Star Wars: Episode VII - The Force Awakens,7.1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Signed Sealed Delivered,7.7,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
The Following,7.5,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
A Plague So Pleasant,6.3,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Shanghai Calling,6.3,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
My Date with Drew,6.6,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [36]:
from sklearn.neighbors import NearestNeighbors

In [37]:
rec_model = NearestNeighbors(metric = 'cosine')
rec_model.fit(data3)

NearestNeighbors(metric='cosine')

In [38]:
data3.index

Index(['Avatar ', 'Pirates of the Caribbean: At World's End ', 'Spectre ',
       'The Dark Knight Rises ',
       'Star Wars: Episode VII - The Force Awakens             ',
       'John Carter ', 'Spider-Man 3 ', 'Tangled ', 'Avengers: Age of Ultron ',
       'Harry Potter and the Half-Blood Prince ',
       ...
       'Primer ', 'Cavite ', 'El Mariachi ', 'The Mongol King ', 'Newlyweds ',
       'Signed Sealed Delivered ', 'The Following             ',
       'A Plague So Pleasant ', 'Shanghai Calling ', 'My Date with Drew '],
      dtype='object', name='movie_title', length=4920)

In [39]:
#data4=data3
data3.index=data3.index.str.strip()

In [40]:
query_movie="X-Men 2"
data3.loc[query_movie, :].values.reshape(1, -1)

array([[7.5, 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

In [41]:
query_movie='Spectre'
#query_movie="Licence to Kill"
dist, ind = rec_model.kneighbors(data3.loc[query_movie, :].values.reshape(1, -1), n_neighbors = 6)

/usr/local/lib/python3.10/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

In [42]:
# query_movie_index=113
# dist, ind = rec_model.kneighbors(data3.iloc[query_movie_index, :].values.reshape(1, -1), n_neighbors = 6)

In [43]:
ind

array([[   2,  140,  213, 1156,  432,  249]])

In [44]:
dist

array([[0.00000000e+00, 7.71344133e-06, 8.14258116e-06, 3.34815674e-05,
        6.58504046e-05, 7.74690018e-05]])

In [45]:
data3.loc[query_movie, :]

imdb_score                6.8
genre1_Action             1.0
genre1_Adventure          0.0
genre1_Animation          0.0
genre1_Biography          0.0
                         ...
content_rating_TV-PG      0.0
content_rating_TV-Y       0.0
content_rating_TV-Y7      0.0
content_rating_Unrated    0.0
content_rating_X          0.0
Name: Spectre, Length: 89, dtype: float64

In [46]:
#data3.iloc[query_movie_index, :]

In [47]:
list(data3.index[ind[0]])[1:]

['Mission: Impossible III',
 'The Bourne Legacy',
 'Licence to Kill',
 'Mission: Impossible',
 'Tomorrow Never Dies']

In [48]:

for i in range(0, len(dist[0])):
    if i == 0:
        print('Top 5 Recommendations for the user who watched the movie :',query_movie)
    else:
        print(i, data3.index[ind[0][i]])

Top 5 Recommendations for the user who watched the movie : Spectre
1 Mission: Impossible III
2 The Bourne Legacy
3 Licence to Kill
4 Mission: Impossible
5 Tomorrow Never Dies